version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      dependencies-github-actions:
        patterns:
          - "*"
      # merged and released automatically
      dependencies-security-updates:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      # merged and released automatically
      dependencies-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
      # merged automatically
      dependencies-development:
        patterns:
          - "*test"
          - "*assert"
      # merged and released automatically
      dependencies-production:
        update-types:
          - "patch"
          - "minor"
      # requires human approval
      dependencies-production-major:
        update-types:
          - "major"