name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches-ignore:
      - 'dependabot/**'
      - 'gh-pages'

jobs:
  build:
    uses: coditory/jvm-workflows/.github/workflows/build.yml@v1
    secrets: inherit
    with:
      debug: true
      java-version: 21
      build-command: ./gradlew build coverage
      snapshot-command: echo "Simulating snapshot publication $NEXT_VERSION"
      # snapshot-command: ./gradlew publishToSonatype -Pversion=%NEXT_VERSION%

  publish-snapshot:
    uses: .github/workflows/release.yml
    if: |
      needs.build.result == 'success' 
      && needs.build.outputs.skipped == 'false'
      && github.event_name == 'pull_request'
    secrets: inherit
    with:
      snapshot: true

  publish-release:
    uses: .github/workflows/release-auto.yml
    if: |
      needs.build.result == 'success' 
      && needs.build.outputs.skipped == 'false'
      && github.event_name == 'push'
      && github.ref_name == github.event.repository.default_branch