name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches-ignore:
      - 'dependabot/**'
      - 'gh-pages'

jobs:
  build:
    uses: coditory/jvm-workflows/.github/workflows/build.yml@v1
    secrets: inherit
    with:
      debug: true
      java-version: 21
      build-command: ./gradlew build coverage

  snapshot:
    uses: ./.github/workflows/release.yml
    needs: build
    if: |
      needs.build.result == 'success'
      && github.event_name == 'pull_request'
    secrets: inherit
    with:
      snapshot: true

  release:
    uses: ./.github/workflows/release-auto.yml
    needs: build
    if: |
      needs.build.result == 'success'
      && github.event_name == 'push'
      && github.ref_name == github.event.repository.default_branch
    with:
      security-updates-only: true