name: Version Check

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - v*

jobs:
  version-check:
    uses: coditory/workflows/.github/workflows/version-check.yml@v1
    secrets: inherit
    with:
      debug: true
      java-version: 21
      version-command: ./gradlew version --quiet
