name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - v*

jobs:
  build:
    uses: coditory/jvm-workflows/.github/workflows/version-check.yml@v1
    # Required to pass codecov token
    secrets: inherit
    with:
      debug: true
      java-version: 21
